name: Deploy React App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies
        run: |
          npm ci
          npm run build

      # Step 4: Rename the `dist` directory to `akcaf-frontend`
      - name: Rename dist to akcaf-frontend
        run: mv ./dist ./akcaf-frontend

      # Step 5: Set up Environment Variables in `.env`
      - name: Set up Environment Variables
        run: |
          echo "VITE_APP_AWS_S3_BUCKET=${{ secrets.VITE_APP_AWS_S3_BUCKET }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_REGION=${{ secrets.VITE_APP_AWS_REGION }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_ACCESS_KEY_ID=${{ secrets.VITE_APP_AWS_ACCESS_KEY_ID }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.VITE_APP_AWS_SECRET_ACCESS_KEY }}" >> ./akcaf-frontend/.env

      # Step 6: Debug - Verify directory structure and files
      - name: Debug Build Output
        run: |
          ls -la ./akcaf-frontend
          cat ./akcaf-frontend/.env

      # Step 7: Archive files for deployment
      - name: Archive Files for Deployment
        run: tar -czf deployment.tar.gz ./akcaf-frontend

      # Step 8: Copy Archive to Lightsail
      - name: Copy Archive to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: deployment.tar.gz
          target: ~/deploy-temp/

      # Step 9: Deploy the application on Lightsail
      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            # Extract the uploaded archive
            tar -xzf ~/deploy-temp/deployment.tar.gz -C ~/deploy-temp/
            # Remove the old deployment
            sudo rm -rf /var/www/html/akcaf-frontend
            # Move the new deployment to the appropriate directory
            sudo mv ~/deploy-temp/akcaf-frontend /var/www/html/
            # Clean up temporary files
            sudo rm -rf ~/deploy-temp
            # Restart Nginx to reflect changes
            sudo systemctl restart nginx
