name: Deploy React App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Node.js and dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm ci
          npm run build

      # Step 3: Rename `dist` to `akcaf-frontend`
      - name: Rename dist to akcaf-frontend
        run: mv ./dist ./akcaf-frontend

      # Step 4: Create .env File
      - name: Create .env File
        run: |
          echo "VITE_APP_AWS_S3_BUCKET=${{ secrets.VITE_APP_AWS_S3_BUCKET }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_REGION=${{ secrets.VITE_APP_AWS_REGION }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_ACCESS_KEY_ID=${{ secrets.VITE_APP_AWS_ACCESS_KEY_ID }}" >> ./akcaf-frontend/.env
          echo "VITE_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.VITE_APP_AWS_SECRET_ACCESS_KEY }}" >> ./akcaf-frontend/.env

      # Step 5: Copy files to a temporary directory on the server
      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: ./akcaf-frontend/
          target: ~/deploy-temp/

      # Step 6: Move files to the target directory and restart the server
      - name: Deploy to Target Directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            # Ensure the target directory is clean
            sudo rm -rf /var/www/html/*
            # Move new files to the target directory
            sudo mv ~/deploy-temp/* /var/www/html/
            # Clean up the temporary directory
            sudo rm -rf ~/deploy-temp
            # Clear Nginx cache and restart
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx
