name: Deploy React App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Set Environment Variables for Build
      - name: Set Environment Variables
        run: |
          echo "VITE_APP_AWS_S3_BUCKET=${{ secrets.VITE_APP_AWS_S3_BUCKET }}" >> .env
          echo "VITE_APP_AWS_REGION=${{ secrets.VITE_APP_AWS_REGION }}" >> .env
          echo "VITE_APP_AWS_ACCESS_KEY_ID=${{ secrets.VITE_APP_AWS_ACCESS_KEY_ID }}" >> .env
          echo "VITE_APP_AWS_SECRET_ACCESS_KEY=${{ secrets.VITE_APP_AWS_SECRET_ACCESS_KEY }}" >> .env

      # Step 4: Install Dependencies and Build
      - name: Build React App
        run: |
          npm ci
          npm run build

      # Step 5: Rename `dist` to `akcaf-frontend`
      - name: Rename dist to akcaf-frontend
        run: mv ./dist ./akcaf-frontend

      # Step 6: Upload Files to Lightsail
      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: ./akcaf-frontend/
          target: ~/deploy-temp/

      # Step 7: Move Files to Target Directory and Restart Nginx
      - name: Deploy to Target Directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            # Clean the target directory
            sudo rm -rf /var/www/html/*
            # Move new files to the target directory
            sudo mv ~/deploy-temp/* /var/www/html/
            # Clean up the temporary directory
            sudo rm -rf ~/deploy-temp
            # Clear Nginx cache and restart the server
            sudo rm -rf /var/cache/nginx/*
            sudo systemctl restart nginx
